drop table IF EXISTS likes cascade ;
drop table IF EXISTS friends cascade;
drop table IF EXISTS films_genres cascade ;
drop table IF EXISTS users cascade ;
drop table IF EXISTS friends cascade ;
drop table IF EXISTS films cascade ;
drop table if exists mpa_rating cascade;

create TABLE IF NOT EXISTS mpa_rating
(
    mpa_rate_id integer PRIMARY KEY,
    name varchar(10) NOT NULL 
);

create TABLE IF NOT EXISTS films
(
    film_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    description varchar,
    release_date date,
    duration integer,
    mpa_rate_id integer REFERENCES mpa_rating (mpa_rate_id) ON delete SET NULL
);

create TABLE IF NOT EXISTS genres
(
    genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);

create TABLE IF NOT EXISTS films_genres
(
    film_id bigint NOT NULL,
    genre_id integer NOT NULL,
    CONSTRAINT films_genres_pk PRIMARY KEY (film_id, genre_id),
    CONSTRAINT films_genres_fk1 FOREIGN KEY (film_id) REFERENCES films (film_id) ON delete CASCADE,
    CONSTRAINT films_genres_fk2 FOREIGN KEY (genre_id) REFERENCES genres (genre_id) ON delete CASCADE
);

create TABLE IF NOT EXISTS users
(
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL,
    login varchar(255) NOT NULL,
    name varchar(255),
    birthday date    
);

create TABLE IF NOT EXISTS likes
(
    film_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT likes_pk PRIMARY KEY (film_id, user_id),
    CONSTRAINT likes_fk1 FOREIGN KEY (film_id) REFERENCES films (film_id) ON delete CASCADE,
    CONSTRAINT likes_fk2 FOREIGN KEY (user_id) REFERENCES users (user_id) ON delete CASCADE
);

create TABLE IF NOT EXISTS friends
(
    offeror_id bigint NOT NULL,
    acceptor_id bigint NOT NULL,
    CONSTRAINT friends_pk PRIMARY KEY (offeror_id, acceptor_id),
    CONSTRAINT friends_fk1 FOREIGN KEY (offeror_id) REFERENCES users (user_id) ON delete CASCADE,
    CONSTRAINT friends_fk2 FOREIGN KEY (acceptor_id) REFERENCES users (user_id) ON delete CASCADE
);




